name = "Richard Yang"
description = "Software Developer with passion in automation."
keywords = "Python, C++, Automation, Developer, Test"
image = "jake.webp"
theme = "dark"
primary_color = "#20C20E"
text_align = "center"
gtag_id = "G-33WB8LVHR6"
base_url = "https://thevahidal.github.io/jake"

[[sections]]
direction="row"
item_style= "outline"
[[sections.items]]
title= "Twitter"
url= ""
[[sections.items]]
title="Facebook"
url="https://www.facebook.com/richard.yang.33/"
[[sections.items]]
title="Linkedin"
url="https://www.linkedin.com/in/richard-yang-0a866212b"
[[sections]]
direction="row"
item_style= "outline"
[[sections.items]]
title= "Twitter"
url= ""
[[sections.items]]
title="Facebook"
url="https://www.facebook.com/richard.yang.33/"
[[sections.items]]
title="Linkedin"
url="https://www.linkedin.com/in/richard-yang-0a866212b"

[[sections]]
title="Github Projects"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "MudaeAutoBot"
description = "Non-Locking Selfbot to automate interaction with Mudea Discord Bot"
url = "https://github.com/vivinano/MudaeAutoBot"
[[sections.items]]
title = "Shadowverse Evolve NFC Database"
description = "Community Collection of Character cards to interact with the Shadowberse Evolve APP"
url = "https://github.com/vivinano/Shadowverse_Evolve_Sidekick_NFCDump"

